//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinesoft.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://weblist.com/", ConfigurationName="ServiceReference1.mesinterlistSoap")]
    public interface mesinterlistSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weblist.com/getfingucode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getfingucode(string custbarcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weblist.com/getcpdm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getcpdm(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weblist.com/getdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weblist.com/getseekresult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getseekresult(out string errmsg, string strsql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mesinterlistSoapChannel : onlinesoft.ServiceReference1.mesinterlistSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mesinterlistSoapClient : System.ServiceModel.ClientBase<onlinesoft.ServiceReference1.mesinterlistSoap>, onlinesoft.ServiceReference1.mesinterlistSoap {
        
        public mesinterlistSoapClient() {
        }
        
        public mesinterlistSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mesinterlistSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mesinterlistSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mesinterlistSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getfingucode(string custbarcode) {
            return base.Channel.getfingucode(custbarcode);
        }
        
        public string getcpdm(string barcode) {
            return base.Channel.getcpdm(barcode);
        }
        
        public string getdate() {
            return base.Channel.getdate();
        }
        
        public System.Data.DataSet getseekresult(out string errmsg, string strsql) {
            return base.Channel.getseekresult(out errmsg, strsql);
        }
    }
}
